name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y python3-pip
        pip3 install --no-cache-dir flet==0.26.0 requests python-dateutil pillow 'flet[all]==0.26.0'
        
    - name: Build APK
      run: |
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
