name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          openjdk-17-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake
          
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip
        mv android-ndk-r25b ${ANDROID_SDK_ROOT}/ndk/25.2.9519653
        rm android-ndk-r25b-linux.zip
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-for-android==2023.9.4
        pip install flet==0.26.0 requests python-dateutil pillow
        
    - name: Build APK
      env:
        ANDROID_NDK_HOME: ${{ env.ANDROID_SDK_ROOT }}/ndk/25.2.9519653
      run: |
        p4a create --requirements=python3,flet==0.26.0,requests,python-dateutil,pillow \
                  --private . \
                  --package=com.example.crypto_news_monitor \
                  --name "Crypto News Monitor" \
                  --version 1.0.0 \
                  --bootstrap webview \
                  --sdk-dir $ANDROID_SDK_ROOT \
                  --ndk-dir $ANDROID_NDK_HOME \
                  --arch arm64-v8a \
                  --permission INTERNET \
                  --release
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: crypto-news-monitor
        path: ./*.apk
