name: Build Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet==0.26.0 requests python-dateutil pillow
        pip install pyinstaller
        
    - name: Create assets directory
      run: mkdir -p assets
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --name crypto_news_monitor \
                   --onefile \
                   --windowed \
                   --add-data "assets:assets" \
                   main.py
        
    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: crypto_news_monitor
        path: dist/crypto_news_monitor
