name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet==0.26.0 requests python-dateutil pillow
        
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install Flet CLI
      run: |
        pip install flet-cli==0.26.0
        pip install 'flet[all]==0.26.0'
      
    - name: Create assets directory
      run: mkdir -p assets
      
    - name: Flutter setup
      run: |
        flutter config --no-analytics
        flutter doctor -v
        flutter pub get
        
    - name: Create local.properties
      run: |
        echo "flutter.sdk=$FLUTTER_HOME" > android/local.properties
        
    - name: Build APK
      run: |
        flutter build apk --release
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/app/outputs/apk/release/app-release.apk
